### ISSUE TITLE
Not working any more?

### ISSUE THREAD

**Issue by daemontus** [stoprocent/node-itunesconnect#7]
Hi, I have been using this nifty tool for a while now, but last week it stopped working - requests return no error or result (The callback is never called). Is it officially dead or can I hope for some fix? (I'll try to dig little into this, but I am not big on node, so I doubt I can do anything)

**Comment by daemontus** [comment]
Ok, never mind - found the issue. The itunes connect login site has been updated with new apple login system. I managed to create a workaround, pull request will follow shortly.

**Comment by stoprocent** [comment]
Cool. I didnt have a chance to work on it for some time now as im loaded with daily work. Feel free to fix it :)

**Comment by daemontus** [comment]
Ok, maybe a little premature of me :D The login seems to be working (I have the right cookies - or at least the server is not rejecting me as before), but now I am getting "You don't have access to the PIANO application." errors when requesting anything. Will have to dig deeper. Hopefully will be able to fix it tomorrow. (Anyway, thanks for a great tool :))

**Comment by stoprocent** [comment]
From what I've seen requests made by node-itunesconnect are missing CSRF Header which is sent by the browser. Not sure what is it exactly ...
I did modify login function to 
```Javascript
Connect.prototype.login = function(username, password) {
	var self = this;
	// Login to ITC
	request.post({
		url : self.options.baseURL , 
		headers: {
			"X-Apple-Widget-Key": "22d448248055bab0dc197c6271d738c3",
			"Content-Type": "application/json;charset=UTF-8"
		},
		json: {
			'accountName' 	: username,
			'password'		: password,
			'rememberMe'	: false
		}
	}, function(error, response, body) {

		var cookies = response ? response.headers['set-cookie'] : null;

		// Handle Errors
		if(error || !(cookies && cookies.length)) {
			error = error || new Error('There was a problem with recieving cookies. Please check your username and password.');
			self.options.errorCallback( error );
		}
		else { 
			// Set _cookies and run callback
			self._cookies = cookies;
			self.options.loginCallback(cookies);
			// Start requests queue
			self._queue.resume();
		}
	});
}
```
If you can take it from here it would be great !

**Comment by stoprocent** [comment]
Oh... and

```Javascript
function Connect(username, password, options) {
	// Default Options
	this.options = {
		baseURL				: "https://idmsa.apple.com/appleauth/auth/signin",
		apiURL				: "https://reportingitc2.apple.com/api/",
		concurrentRequests	: 2,
		errorCallback		: function(e) {},
		loginCallback		: function(c) {}
	};
...
```
Different baseURL

**Comment by Balgorn** [comment]
Hey would be great to get an update. Hope you can fix it soon.

**Comment by sthurian** [comment]
Hope so too, same problem here.

**Comment by stoprocent** [comment]
Ok guys I will have a look after work today and let you know.

**Comment by daemontus** [comment]
Pull request pushed - I ended up not using the request library cookie jar, because it was causing the 500s - not sure why, probably some token reuse or something, but extracting only the account and context cookie solved everything. Hopefully Apple won't tinker with the login system again (soon). Anyway, please test and merge it, if everything is fine, you can close this issue :)

**Comment by Balgorn** [comment]
nice thanks for your time. Could the npm package be updated/released after for easier integration?

**Comment by stoprocent** [comment]
Great job! nmp is also updated!

**Comment by Balgorn** [comment]
@stoprocent thank you too :)

**Comment by stoprocent** [comment]
I had some problems to get it working but it should be ok now.
I had to add ```X-Apple-Widget-Key``` header to login request to get ```myacinfo``` cookie.
Also old login method was still there ;)

**Comment by daemontus** [comment]
Oh damn, my bad - I moved the changes there from my other working copy and I guess I must have made a typo while copying. Thanks for the fix. 

Anyway, that cookie is interesting - I haven't seen that anywhere in my cookies (like at all).

**Comment by stoprocent** [comment]
It is ```HTTP header``` not a cookie. I guess it is something like ```client_id``` etc. 
I should probably keep an eye on it beacuse its hardcoded somewhere in their javascript and it can be changed at any point.

I will have a look again when I have a bit more time. 
Thanks again for the pull request :+1:

**Comment by daemontus** [comment]
Oh, yeah, right...I haven't really checked the headers, nvm... (Worked for me without it) 

Anyway, thanks for the great tool and code safe :)

**Comment by sthurian** [comment]
Great ! It works for me now, too - thank you for this !
