### ISSUE TITLE
Question about Itunes error-codes

### ISSUE THREAD

**Issue by AloneCoder** [stoprocent/node-itunesconnect#9]
Hello!
First of all, thank you for this library
I'm trying to rewrite it in PHP, but experience an error
So, I catch both cookies myacinfo and itctx, but when I try to fetch report with them I gain 403 response code and response body like this JSON
``` {"error-code":"SL9009", "message":"You do not have access to the application PIANO."}```
Maybe you've seen this already and can help me?

**Comment by sthurian** [comment]
Check your user-roles on iTunes connect

**Comment by AloneCoder** [comment]
@sthurian what role should I have? I'm able to view all the data via web-access to sales and trends

**Comment by sthurian** [comment]
I am not sure (i'm a Android and node.js guy), but i think you need to be at least developer with your account. In doubt: just try it.

Otherwise i have no idea

**Comment by AloneCoder** [comment]
Thanks for your response!
Found out that symbol "|" in itctx-cookie was url-encoded
